config/routes.rb
NorthBlog::Application.routes.draw do
  
  root :to => 'posts#index'
  
  resources :categories
  resources :pages
  resources :sessions
  resources :users
  resources :posts
  
  
  match "/arkiv" => "archives#index"
  
  get "sessions/new"
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :title
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :catgegory_id, :content, :title, :user_id
  belongs_to :user

  def self.search(search)
  if search
    find(:all, :order => "created_at DESC", :conditions => ['content LIKE ? OR title LIKE ?', "%#{search}%","%#{search}%"])
  else
    find(:all)
  end
end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  attr_accessible :fname, :lname, :password, :password_confirmation, :content
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
    protect_from_forgery
  
  private

def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end
helper_method :current_user

def authorize
  redirect_to login_url if current_user.nil?
  end
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
  

   def index
 
end
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def index
    
  end
  def archive
    
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json 

  def index
@posts = Post.search(params[:search])

  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
    
def create
  user = User.find_by_fname(params[:fname])
  if user && user.authenticate(params[:password])
    session[:user_id] = user.id
    #redirect_to "/admin", :notice => "Logged in som " + user.fname
    redirect_to "/users"
  else
    
    #redirect_to "/login", :notice => "Feil brukernavn eller passord"
  end
end

def destroy
  session[:user_id] = nil
  redirect_to "/index", :notice => "Logged out!"
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_filter :authorize
  def index
      
    @users = User.all
   
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
        
      redirect_to '/users'
    else
      render :action => 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
     redirect_to '/users'
    else
      render :action => 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to '/users'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archives_helper.rb
module ArchivesHelper
  
  
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  
 
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/archives/index.html.erb

   
<div id="pageHeader"> <h1>Blog Arkiv</h1></div>

    
    <% posts = Post.all(:order => "created_at DESC") %>
    <% post_months = posts.group_by { |t| t.created_at.beginning_of_month } %>


	<% n = 0 %>

    <% post_months.each do |month, posts| %>
    <div id="month">
    <a href="javascript:void(0)"onclick="toggleMe('archiveList<%= n %>', this) "><%=  month.strftime("%B %Y") %></a><img src="https://dl.dropbox.com/u/7238474/north/arrow.png" alt="arrow"/>
    </div>
    <div id="archiveList<%= n %>" class="blogsMonth" style="display:<% if n == 0 %> block <% else %> none <%end%>;">
    <ul>
       
		<% for post in posts %>
		<% u = User.find_by_id(post.user_id)%>
   
        	<li><%= link_to post.title.capitalize, post %> av <%= link_to u.fname.capitalize + " " +  u.lname.capitalize, u  %></li>
        <% end %>
    </ul>
    </div>
    <% n += 1%>
    <% end %>


app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>



<% @categories.each do |category| %>

<%= link_to category.title, category %><br/>


<%= link_to 'Show', category %>
<%= link_to 'Edit', edit_category_path(category) %>
<%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %><br/>

<% end %>


<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<div id="pageHeader"><h1><%= @category.title %> </h1></div>



<% Post.where(:catgegory_id => @category.id).order('created_at DESC').each do |p|%>
<% user = User.find_by_id(p.user_id)%>
<h3><%=link_to p.title.capitalize, p%> </h3> av <%= link_to user.fname.capitalize + " " +user.lname.capitalize, user%>
<small><%= p.created_at.strftime("%d-%m-%Y")%></small>
<p><%= p.content.truncate(140)%></p>
<% end %>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NorthBlog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body >
	
	
	<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1&appId=508282202555713";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>



	<div id="headerWrapper">
		<header>
			
			<div id="logo">
			<img src="https://dl.dropbox.com/u/7238474/north/timthumb3.png">
			</div>
			
		</header>		
	</div>
	
	<div id="navWrapper">
		<nav>
 			<div id="searchBox">
 				
			<%= form_tag posts_path, :method => :get do %>  
			
				<%= text_field_tag :search, params[:search], :class => 'searchField' %>  
				<%= submit_tag "Søk", :name => nil, :class => 'searchButton' %>  
			<% end %>
 			</div>
			<ul>
				<li><%= link_to 'Hjem', root_path%></li>
				<li><a href="javascript:void(0)"  onclick="showBloggers('bloggers', 0, 'k');showCategories('categories', 1, 'c');" id="k"> Bloggere</a>	</li>
				<li><a href="javascript:void(0)"  onclick="showCategories('categories', 0, 'c');showBloggers('bloggers', 1, 'k');" id="c"> Kategorier</a></li>
				<li><a href="/arkiv">Arkiv</a></li>
			</ul>
			
		</nav>
		
	</div>
	<div id="subMenuWrapper">
		
		<div id="categories" class="subMenu">
			<% if Category.count > 0 %>
			<div style="padding:10px 5px 0 5px;float:left;">
				<ul>
				<% Category.all.each do |c|%>
				<div style="float:left;padding: 0 20px 0 0">
				<li>
				<%= link_to c.title.capitalize, c%>	
				</li>
					</div>
				<% end %>
				</ul>
			</div>
			<% end %>
			</div>
		
		
		
		<div id="bloggers" class="subMenu">
			<% if User.count > 0 %>
			<div style="padding:10px 5px 0 5px;float:left;">
				<ul>
				<% User.all.each do |u|%>
				<div style="float:left;padding: 0 20px 0 0">
					<li>
				<%= link_to u.fname.capitalize + " " + u.lname.capitalize, u%>	
				</li>
					</div>
				<% end %>
				</ul>
			</div>
			<% end %>
			</div>
			</div>
	<div id="wrapper">

		<div id="innerWrapper">
		<aside>
		
			<div id="pic"><div id="opa"><h3 style="color:#fff;margin:15px 0 0 10px;padding:0;">Følg oss på facebook</h3></div><img src="https://dl.dropbox.com/u/7238474/north/shutterstock_70010218_small.jpg"  alt="bilde"/></div>
			<div id="facebook">
			<div class="fb-like" data-href="http://www.facebook.com/northsec" data-send="true" data-width="300" data-show-faces="true" style="float:left;"></div>
			
			</div>
			<div id="pic"><div id="opa1"><h3 style="color:#fff;margin:15px 0 0 10px;padding:0;">Les våre analyser</h3></div><img src="https://dl.dropbox.com/u/7238474/north/analyse.jpg"  alt="bilde"/></div>
		</aside>
	<article>
<section>
<%= yield %>
</section>
</article>
</div>
</div>
<div id="footerWrapper">

	<footer></footer>
	
</div>
</body>
</html>

app/views/pages/index.html.erb
<h1>Velkommen</h1>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
  	<% if current_user != nil %>
  	 <%= f.label current_user.id  %><br />
  	<%= f.hidden_field :user_id, :value => current_user.id %>
  	<% else %>
  	<%= f.hidden_field :user_id, :value => User.first.id %>
  	<% end %>
   
   
  </div>
  <div class="field">
  	
  	<%= f.collection_select(:catgegory_id, Category.all, :id, :title ) %>
  	
  
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div id="pageHeader"><h1>Nyeste innlegg</h1>
				  

</div>

<% n = 0%>
<% @posts.each do |post| %>
<% user = User.find_by_id(post.user_id)%>
	<% if n == 0 %>
		<div id="firstPost">
			<div id="avatar"><img src="https://dl.dropbox.com/u/7238474/north/avatar.jpg" style="margin:5px 0 0 0;" alt="avatatPicture"/></div>
			<div class="heading"><h1><%= post.title.capitalize %></h1></div>
			<small><%= post.created_at.strftime("%d-%m-%Y") %></small>
			<small><i><%= link_to user.fname.capitalize + " " + user.lname.capitalize, user, :class => "author" %></i></small>
			<p><%= post.content.truncate(700)%></p>
			<p><%= link_to 'Les mer...', post %></p>
			<%= link_to 'edit', edit_post_path(post)%>
		</div>
		
		<div id="postBorder"></div>
	<% else %>
		<div id="splitViewPost">
			<div id="avatar"><img src="https://dl.dropbox.com/u/7238474/north/avatar.jpg" alt="avatatPicture"/></div>
			<div class="heading"><h3><%= post.title%></h3></div>
			<small><%= post.created_at.strftime("%d-%m-%Y") %></small>
			<small><i><%= link_to user.fname.capitalize + " " + user.lname.capitalize, user %></i></small>
			<p><%= post.content.truncate(200)%></p>
			<p><%= link_to 'Les mer...', post %></p>
			<%= link_to 'edit', edit_post_path(post)%>
		</div>
		<% if n.even?%>
		<div id="postBorder"></div>
		<% end %>
	<% end %>


	<%  n += 1%>
<% end %>

<div id="link">
<%= link_to 'New Post', new_post_path %>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<%  cat = Category.find_by_id(@post.catgegory_id)%>
<% user = User.find_by_id(@post.user_id)%>
<div id="pageHeader"><h1><%= link_to cat.title, cat %> </h1></div>
<div id="avatar"><img src="https://dl.dropbox.com/u/7238474/north/avatar.jpg"  alt="avatatPicture"/></div>

<h1> <%= @post.title.capitalize %> </h1>
<small><%= @post.created_at.strftime("%d-%m-%Y") %></small>
<small><i><%= link_to user.fname.capitalize + " " + user.lname.capitalize, user %></i></small>

<p>
  <%= @post.content %>
</p>



<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>
<div id="postBorder"></div>

<div id="splitViewPost">
<h3>Mer fra denne brukeren:</h3>
<ul>
<% Post.where(:user_id => user.id).limit(10).order('created_at DESC').each do |p|%>
<% if @post.id != p.id %>

<li><%= link_to p.title.capitalize, p %></li>
<%end%>
<% end %>
</ul>
</div>

<div id="splitViewPost">
	<h3>Mer i denne kategorien:</h3>
	<ul>
	<% Post.where(:catgegory_id => @post.catgegory_id).order('created_at DESC').limit(10).each do |p|%>
	<% if @post.id != p.id %>
	<li><%= link_to p.title.capitalize, p %></li>
	<% end %>
	<% end %>
	</ul>
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

  <p>
    <%= f.label "Fornavn" %><br />
    <%= f.text_field :fname %>
  </p>
  <p>
    <%= f.label "Etternavn" %><br />
    <%= f.text_field :lname %>
  </p>
  
  <p>
  	    <%= f.label "Bio" %><br />
    <%= f.text_area :content %>
  </p>
  <p>
    <%= f.label "Passord" %><br />
    <%= f.password_field :password %>
  </p>
   <p>
    <%= f.label "Gjenta passord" %><br />
    <%= f.password_field :password_confirmation %>
  </p>

	  
  <p><%= f.submit "Lagre"%></p>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Fname</th>
    <th>Lname</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.fname %></td>
    <td><%= user.lname %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div id="pageHeader"><h1><%= @user.fname.capitalize + " " + @user.lname.capitalize %> </h1></div>
<div id="avatarBig"><img src="https://dl.dropbox.com/u/7238474/north/avatar.jpg" />
	<p><%= @user.content %></p>
	
</div>

<div id="postBorder"></div>
<div id="splitViewPost">
<h3>Mer fra denne brukeren:</h3>
<ul>
<% Post.where(:user_id => @user.id).order('created_at DESC').each do |p|%>

	<li>
<%= link_to p.title.capitalize, p  %>
<small><%= p.created_at.strftime("%d-%m-%Y") %></small>
</li>

<% end %>
</ul>
</div>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>